# Generated by Django 5.1.1 on 2024-10-07 19:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dirección',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('contacto', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='ES')),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Direcciones.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Direcciones.provincia'),
        ),
    ]
