# Generated by Django 5.1.2 on 2024-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Direcciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirección',
            name='codigo_postal',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
