# Generated by Django 5.1.2 on 2024-10-24 17:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Direcciones', '0002_dirección_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirección',
            name='contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='AR'),
        ),
    ]
