# Generated by Django 5.1.2 on 2025-03-17 04:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Direcciones', '0004_alter_ciudad_idciudad_alter_provincia_idprovincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=32)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='dirección',
            name='ciudad',
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDepartamento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='Direcciones.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMunicipio', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='Direcciones.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('contacto', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='AR')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('coordenada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='Direcciones.coordenada')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='Direcciones.municipio')),
            ],
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
