# Generated by Django 5.1.2 on 2025-03-17 15:06

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Direcciones', '0004_alter_ciudad_idciudad_alter_provincia_idprovincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('idCoordenada', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=32)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='dirección',
            name='ciudad',
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='idCiudad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='Direcciones.provincia'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('contacto', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='AR')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='Direcciones.ciudad')),
                ('coordenada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='Direcciones.coordenada')),
            ],
        ),
    ]
