# Generated by Django 5.1.2 on 2025-03-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0009_alter_compra_direccion'),
        ('Direcciones', '0005_coordenada_remove_dirección_ciudad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dirección',
        ),
    ]
