# Generated by Django 5.1.2 on 2025-03-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Direcciones', '0007_direccion_depto_direccion_piso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='idProvincia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
