# Generated by Django 5.1.2 on 2025-07-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Direcciones', '0009_alter_provincia_idprovincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='coordenada',
        ),
        migrations.DeleteModel(
            name='Coordenada',
        ),
    ]
