# Generated by Django 5.1.2 on 2025-07-27 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Direcciones', '0010_remove_direccion_coordenada_delete_coordenada'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
