# Generated by Django 5.1.2 on 2024-10-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('Usuarios', '0003_remove_reseña_funko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='reseña',
            name='funko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.funko'),
        ),
    ]
