# Generated by Django 5.1.2 on 2024-10-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_remove_usuario_favoritos_reseña_funko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
    ]
