# Generated by Django 5.1.2 on 2024-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('Usuarios', '0007_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos', to='Productos.funko'),
        ),
    ]
