# Generated by Django 5.1.2 on 2024-11-04 01:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_usuario_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='AR'),
        ),
    ]
