# Generated by Django 5.1.2 on 2024-11-04 02:28

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_alter_usuario_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
