# Generated by Django 5.1.1 on 2024-10-07 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoría',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('idDescuento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(editable=False, max_length=100)),
                ('porcentaje', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_expiracion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Funko',
            fields=[
                ('idFunko', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripción', models.TextField()),
                ('is_backlight', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.IntegerField()),
                ('categoría', models.ManyToManyField(to='Productos.categoría')),
            ],
        ),
        migrations.CreateModel(
            name='FunkoDescuento',
            fields=[
                ('idFunkoDescuento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.descuento')),
                ('funko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.funko')),
            ],
            options={
                'unique_together': {('funko', 'descuento', 'fecha_inicio', 'fecha_expiracion')},
            },
        ),
        migrations.AddField(
            model_name='funko',
            name='descuentos',
            field=models.ManyToManyField(related_name='funkos', through='Productos.FunkoDescuento', to='Productos.descuento'),
        ),
    ]
