# Generated by Django 5.1.2 on 2024-10-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='fecha_expiracion',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='fecha_inicio',
        ),
    ]
