# Generated by Django 5.1.2 on 2024-10-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_remove_descuento_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funko',
            name='descuentos',
        ),
    ]
