# Generated by Django 5.1.2 on 2025-03-01 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_remove_funko_descuentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The public id of the uploaded file', max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(help_text='The original name of the uploaded image', max_length=100)),
                ('width', models.IntegerField(help_text='Width in pixels')),
                ('height', models.IntegerField(help_text='Height in pixels')),
                ('format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='funko',
            name='imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.image'),
        ),
    ]
