# Generated by Django 5.1.2 on 2025-03-01 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_image_funko_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('idImagen', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(help_text='Identificador en Cloudinary o S3', max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('nombre', models.CharField(help_text='Nombre original de la imagen', max_length=100)),
                ('ancho', models.IntegerField()),
                ('alto', models.IntegerField()),
                ('formato', models.CharField(max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funko',
            name='imagen',
        ),
        migrations.AddField(
            model_name='funko',
            name='imagenn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.imagen'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
