# Generated by Django 5.1.2 on 2025-03-01 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_imagen_remove_funko_imagen_funko_imagenn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funko',
            old_name='imagenn',
            new_name='imagen',
        ),
    ]
