# Generated by Django 5.1.2 on 2025-03-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_rename_imagenn_funko_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funko',
            name='imagen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.imagen'),
        ),
    ]
