# Generated by Django 5.1.2 on 2025-03-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_alter_funko_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
