# Generated by Django 5.1.2 on 2025-07-27 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_alter_descuento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funko',
            name='precio',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
