# Generated by Django 5.1.1 on 2024-10-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compras', '0001_initial'),
        ('Direcciones', '0001_initial'),
        ('Productos', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Compras.carrito'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='funko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.funko'),
        ),
        migrations.AddField(
            model_name='compra',
            name='carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Compras.carrito'),
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Direcciones.dirección'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
    ]
