# Generated by Django 5.1.2 on 2024-10-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0003_compraitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
