# Generated by Django 5.1.2 on 2024-11-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0004_compraitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='subtoal',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
