# Generated by Django 5.1.2 on 2024-11-04 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0005_carritoitem_subtoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='subtoal',
        ),
    ]
