# Generated by Django 5.1.2 on 2024-11-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0006_remove_carritoitem_subtoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
