# Generated by Django 5.1.2 on 2025-03-17 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0008_remove_compra_carrito'),
        ('Direcciones', '0005_coordenada_remove_dirección_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Direcciones.direccion'),
        ),
    ]
