# Generated by Django 5.1.2 on 2025-07-20 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0009_alter_compra_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='envio',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='compra',
            name='envio',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
