# Generated by Django 5.1.2 on 2025-07-27 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0010_carrito_envio_compra_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
